### PR TITLE
fix cancel button by removing min-height

### LINKED ISSUE #377: 0.3.14 options to "Proceed" or "cancel" are unable to be pressed
Having a print running, then selecting cancel has a prompt come up that previously had buttons for proceed or cancel. Both of these buttons are hidden from view, somewhere below the nav bar. I've tested with chrome, edge, and safari on my iphone and all of them have the buttons missing.

**Noteable: I am using "small" text option in touchui settings**

IMG_1491

### PR DESCRIPTION
**Pull request by tedder**
Fixes #377. Not sure if there's a larger change you'd like to make, but this is the minimal change to fix the problem.

I have not generated the output. I assume you will do so when cutting a release.

### CODE REVIEW

**Comment by dchauran** [comment]
@BillyBlaze it looks like you've been away for a bit, but this is fairly critical, as it results in users being unable to cancel prints, which is at best a hassle, and at worst a safety issue. Would you mind allowing this one small change in? I have personally tested it on Android and iOS.

**Comment by tedder** [comment]
evil bot

**Comment by BillyBlaze** [comment]
sorry I dont have time yet, but I'll have a look at this as soon as possible.  With the tags the bot wont complain.

p.s. dont blame the bot, its doing my instructions.

**Comment by tedder** [comment]
I'm not blaming the bot, that's how I respond to my own bots too :)

**Comment by BillyBlaze** [comment]
be nice to the bots; one day you will be their slave ;-)

**Comment by albertoxamin** [comment]
> @BillyBlaze it looks like you've been away for a bit, but this is fairly critical, as it results in users being unable to cancel prints, which is at best a hassle, and at worst a safety issue. Would you mind allowing this one small change in? I have personally tested it on Android and iOS.

It is even worse if you have installed the PSUControl plugin. You can't even give power the printer to start a print 😢

**Comment by BillyBlaze** [comment]
Thanks for the pull-request. This issue is fixed on the maintenance branch and @tedder already confirmed that its working.

**Pull request closed without merging**
